### ISSUE TITLE
Does not work with Teensy 4.0

### ISSUE THREAD

**Issue by Nate711** [adafruit/Adafruit_ICM20649#16]
Just in case other users encounter the same problem, icm.beginSPI(cs_pin) works with Teensy 4.0, but not icm.beginSPI(cs_pin, sck_pin, etc). I suspect it's due to how the library tries to use port registers.

**Comment by ladyada** [comment]
@kurte may be a good thing to investigate, this library does not do anything special with port registers that would make bitbang SPI not work

**Comment by KurtE** [comment]
@ladyada  - will try to take a look.  I don't have the hardware, and I don't see anywhere right now to get one, except maybe ebay from Germany... 

@Nate711 - If you have not already done so, best to post up on PJRC forum,  hopefully with additional details, like which hardware you are using, how do you have it hooked up, what software you are running, and what is the specific issue? 

Preferably with simple code example showing the issue.

**Comment by KurtE** [comment]
Quick update: 
Again I don't have any of these, nor can I find any of them currently available... 
@mjs513 do you by chance have one?

But: I do see that it is probably not working properly.  If I run your
adafruit_icm20948 test program  and configure it for hardware SPI, on Logic Analyzer I see:

![image](https://user-images.githubusercontent.com/1558080/166264517-a2ec7b47-c400-4c71-9298-f1407160026d.png)

Again I have nothing plugged in, ... Just T4 and LA

When I configure it for Software SPI I see:
![image](https://user-images.githubusercontent.com/1558080/166264696-20929283-b9c2-4268-a78f-88050806bf3f.png)

So the clock output does not appear to be working

**Comment by mjs513** [comment]
@KurtE - I do have a Sparkfun ICM-20948 that I can give it a try with but will have to be later this afternoon as I am off soon for an appointment.

**Comment by KurtE** [comment]
Quick update, I know the issue is with the Adafruit_SpiDevice.h/.cpp  for the IMXRT.

The issue is: 
```
#if defined(__AVR__) || defined(TEENSYDUINO)
typedef volatile uint8_t BusIO_PortReg;
typedef uint8_t BusIO_PortMask;
#define BUSIO_USE_FAST_PINIO
```
The issue is that on T4.x these registers are 32 bits not 8...
And the SPI clock does not show up. 
```
#if defined(__AVR__) || defined(TEENSYDUINO)
#if defined(__IMXRT1062__) // Teensy 4.x
typedef volatile uint32_t BusIO_PortReg;
typedef uint32_t BusIO_PortMask;
#else
typedef volatile uint8_t BusIO_PortReg;
typedef uint8_t BusIO_PortMask;
#endif
#define BUSIO_USE_FAST_PINIO

```

But not sure I like it... 

That is the code then does things like:
```
#ifdef BUSIO_USE_FAST_PINIO
        *clkPort |= clkPinMask; // Clock high
#else
        digitalWrite(_sck, HIGH);
#endif
```
Problem is, that if by chance you get an interrupt in between the time, this code will read the current state of clkPort and the time it writes it back out, and that interrupt changes one or more pins on the port, your code will then walk over those changes. 

It is not a problem on the T3.x as on the M4 type boards we are using bitband support, so your writes will only touch one pin. 

But M7 boards do not have bitband.  instead the ports do have three additional registers:

```
        volatile uint32_t DR_SET;              // 84
        volatile uint32_t DR_CLEAR;            // 88
        volatile uint32_t DR_TOGGLE;           // 8C
```

Which only set those pins, or clear or toggle those pins who you pass a high value to... 
I am not sure if you have this library working on other M7 level processors as well? 

So not sure how you would want to resolve this...  Options include;
a) on T4 use digitalWrite?

b) Special case it...
If it were my library what I would probably do for a variety of reasons would be to remove most of code that
looks like:
```
#ifdef BUSIO_USE_FAST_PINIO
        *clkPort |= clkPinMask; // Clock high
#else
        digitalWrite(_sck, HIGH);
#endif
```
and instead have something like:
```
setClockHigh().
```

And have each type define their own handlers for this
```
inline void setClockHigh() {
        *clkPort |= clkPinMask; // Clock high
}
```
...
```
inline void setClockHigh() {
        digitalWrite(_sck, HIGH);
}
```

and in this case:
```
inline void setClockHigh() {
        clkPort->DR_SET|= clkPinMask; // Clock high
}
```

But I don't have all of the setups to handle this. and not sure you would more #elif
in all of these code areas. 

Thoughts?

**Comment by ladyada** [comment]
@KurtE 
```
#if defined(__IMXRT1062__) // Teensy 4.x

typedef volatile uint32_t BusIO_PortReg;
typedef uint32_t BusIO_PortMask;

#elif defined(__AVR__) || defined(TEENSYDUINO)

typedef volatile uint8_t BusIO_PortReg;
typedef uint8_t BusIO_PortMask;

#endif
```
is best, please try that and if it works submit a PR!

**Comment by KurtE** [comment]
@ladyada 

As I mentioned in the previous post, it will leave you with the possibility of pin states being clobbered. 

I have seen this before and tore out what remaining hair I don't have trying to figure out why some random pin had it's state clobbered.  Like if you have an intervalTimer and that timer toggles an IO pin... 

I know that the simple fix mentioned will get the clock pin running again... But can not test the device.

@mjs513 does have one though.

**Comment by ladyada** [comment]
ok we wouldnt really let people use soft SPI pins for that purpose. sounds like best to just disable fast IO access for T4 then? can you try ifdefing that? it should still be plenty fast

**Comment by mjs513** [comment]
Looks like I am late.  I did try it on ice board and yep only works with
the car pin specified. Checked the sparkfun implementation and it only uses
the cs pin as well.  One thing I did notice is the allow a max spi clock of
7mhz while the adafruit version uses mhz

**Comment by KurtE** [comment]
Hi @ladyada  and @mjs513  - I did a more complex possible fix, which probably needs some testing...

it is up in the Fork/Branch: https://github.com/KurtE/Adafruit_BusIO/tree/T4x

I did some of the stuff I mentioned, to help hopefully clean some of the stuff up in not having to see lots of #if statements..

So for example the main code for a couple modes looks like:
```
      if (_dataMode == SPI_MODE0 || _dataMode == SPI_MODE2) {
        towrite = send & b;
        if ((_mosi != -1) && (lastmosi != towrite)) {
          setMosi(towrite);
          lastmosi = towrite;
        }

        setClkHigh();

        if (bitdelay_us) {
          delayMicroseconds(bitdelay_us);
        }

        if (_miso != -1) {
          if (getMisoState()) {
            reply |= b;
          }
        }

        setClkLow();
      } else { // if (_dataMode == SPI_MODE1 || _dataMode == SPI_MODE3)

```

Then these methods are in the .h file:
```
#ifdef BUSIO_USE_FAST_PINIO
  BusIO_PortReg *mosiPort, *clkPort, *misoPort, *csPort;
  BusIO_PortMask mosiPinMask, misoPinMask, clkPinMask, csPinMask;

#if defined(__IMXRT1062__) // Teensy 4.x
  //#define portOutputRegister(pin)  ((digital_pin_to_info_PGM[(pin)].reg + 0))
  //#define portSetRegister(pin)     ((digital_pin_to_info_PGM[(pin)].reg + 33))
  //#define portClearRegister(pin)   ((digital_pin_to_info_PGM[(pin)].reg + 34))
  //#define portToggleRegister(pin)  ((digital_pin_to_info_PGM[(pin)].reg + 35))

  inline void setMosi(bool towrite) {
    if (towrite)
      *(mosiPort + 33) = mosiPinMask;
    else
      *(mosiPort + 34) = mosiPinMask;
  }
  inline void setClkHigh() { *(clkPort + 33) = clkPinMask; }
  inline void setClkLow() { *(clkPort + 34) = clkPinMask; }
  inline void setCSHigh() { *(csPort + 33) = csPinMask; }
  inline void setCSLow() { *(csPort + 34) = csPinMask; }
  inline bool getMisoState() { return (*misoPort & misoPinMask); }
#else
  inline void setMosi(bool towrite) {
    if (towrite)
      *mosiPort |= mosiPinMask;
    else
      *mosiPort &= ~mosiPinMask;
  }
  inline void setClkHigh() { *clkPort |= clkPinMask; }
  inline void setClkLow() { *clkPort &= ~clkPinMask; }
  inline void setCSHigh() { *csPort |= csPinMask; }
  inline void setCSLow() { *csPort &= ~csPinMask; }
  inline bool getMisoState() { return (*misoPort & misoPinMask); }
#endif
#else
  inline void setMosi(bool towrite) { digitalWrite(_mosi, towrite); }
  inline void setClkHigh() { digitalWrite(_sck, HIGH); }
  inline void setClkLow() { digitalWrite(_sck, LOW); }
  inline void setCSHigh() { digitalWrite(_cs, HIGH); }
  inline void setCSLow() { digitalWrite(_cs, LOW); }
  inline bool getMisoState() { return (digitalRead(_miso)); }
#endif
```
And I am sort of hacking it for T4.x knowing that the DR_SET and DR_CLEAR registers offsets are and use them.

Let me know if this is too hard core, in which case can simply change header file in IMXRT case to not
set the BUSIO_USE_FAST_PINIO

**Comment by ladyada** [comment]
id rather have one function with multiple ifdefs than multiple functions defined. also makes doxygen/clang less upset

**Comment by KurtE** [comment]
> id rather have one function with multiple ifdefs than multiple functions defined. also makes doxygen/clang less upset

Understood, I will punt for now...

So far I have not seen any messages back from the automatic checkers... For private functions can you not simply 
mark it with:
```
#ifndef DOXYGEN_SHOULD_SKIP_THIS

 /* code that must be skipped by doxygen */

#endif /* DOXYGEN_SHOULD_SKIP_THIS */
```

Also I did run the code through clang-format -i

FYI - it worked on T4 and T3.5... I did find that I had a Sparkfun version of the board in my stuff.

**Comment by ladyada** [comment]
yeah but we do want it doxygened!

**Comment by KurtE** [comment]
> yeah but we do want it doxygened!

Understood, although usually I would expect this for public functions...  Not private ones.

Anyway it is taken care of.... 

Side note: 
In all of the cases now using the FAST IO, where:
```
#ifdef BUSIO_USE_FAST_PINIO
  BusIO_PortReg *mosiPort, *clkPort, *misoPort, *csPort;
  BusIO_PortMask mosiPinMask, misoPinMask, clkPinMask, csPinMask;
#endif
 
```
The csPort and csPinMask are set but never used. 

Instead the code uses:
```
/*!
 *    @brief  Assert/Deassert the CS pin if it is defined
 *    @param  value The state the CS is set to
 */
void Adafruit_SPIDevice::setChipSelect(int value) {
  if (_cs == -1)
    return;
  digitalWrite(_cs, value);
}
```
Now off to the next distraction.

**Comment by ladyada** [comment]
thank you!
